import 'tailwindcss/tailwind.css'
import '../components/css/index.css'
import Header from '../components/Header'
import Footer from '../components/Footer.tsx'
import StoreProvider from './StoreProvider'

export const metadata = {
  title: "E-Commerce Project",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {

  console.log("Entry file executed!");
  return (
    <html lang="en">
      <body className='relative'>
          <StoreProvider>
            <Header />
          <main className='pt-[10vh] pb-[15vh]'>
            <div className='min-h-[60vh] pr-6'>
              {children}
              </div>
          </main>
          <Footer className='absolute bottom-0' />
          
          </StoreProvider>
      </body>
    </html>
  );
}
